---
label: project
hide_body: true
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
  default: Eye Logo
- name: image
  label: Image
  type: file
  description: 1440 by 1440px
  hidden: false
  default: "/uploads/Eye-1.png"
- type: color
  name: background_color
  config:
    color_format: Hex
    required: true
  label: Background Color
  default: "#F5A623"
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- type: datetime
  config:
    required: true
    date_format: YYYY
  hidden: false
  label: Year
  name: year
pages:
- Test Project/icon-for-target-s-first-ipad-app.md
